"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import json
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# I put all all the sensitive data in ˜/data.json
data_path = Path.home() / 'data.json'
with open(data_path, 'r') as f:
    data = json.load(f)

# Here are my own constants that I want to use in settings
SERVER_TYPE = data.get("server_type", "dev")
STRIPE_PRIVATE_KEY = data.get("stripe_private_key")

# Set the Stripe Private Key as a system environment variable so that it can be accessed in users.py
os.environ["STRIPE_PRIVATE_KEY"] = STRIPE_PRIVATE_KEY
# Set the OpenAI API and Gemini API keys as system environment variables so that they can be accessed in chatbot.py
os.environ["OPENAI_KEY"] = data.get("openai_key")
os.environ["GEMINI_KEY"] = data.get("gemini_key")

SECRET_KEY = data.get("django_secret")
# SECURITY WARNING: don't run with debug turned on in production!
if SERVER_TYPE == 'prod':
    DEBUG = False
else:
    DEBUG = True



if SERVER_TYPE == 'prod':
    ALLOWED_HOSTS = ['app.vitamova.com']
    CSRF_TRUSTED_ORIGINS = ['https://app.vitamova.com']
elif SERVER_TYPE == 'dev':
    ALLOWED_HOSTS = ['dev.app.vitamova.com']
    CSRF_TRUSTED_ORIGINS = ['https://dev.app.vitamova.com']

LOGIN_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # allauth apps
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google'
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": data.get("google_client_id"),
            "secret": data.get("google_client_secret"),
            "key": ""
        },
    "SCOPE": ["profile", "email"],
    "AUTH_PARAMS": {"access_type": "online"},
    }    
}


ACCOUNT_UNIQUE_EMAIL = True

# Make social signup automatic when possible
SOCIALACCOUNT_AUTO_SIGNUP = True

# Usually for Google you want:
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True

USE_X_FORWARDED_HOST = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "vitamova",
        "USER": "webapp",
        "PASSWORD": data.get("database_password"),
        "HOST": "vitamova-db.cluster-cartvcorpihi.us-east-1.rds.amazonaws.com",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
